name: Docker Push image

### Trigger on push to branch
on:
  push:
    branches: [master]

### env variables
env:
  IMAGE_NAME: cicd-workflow-d3
  TEST_TAG: ${{ secrets.DOCKER_HUB_USERNAME }}/cicd-workflow-d3:test


jobs:
  run-npm-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: v1-node-dependencies-${{ hashFiles('./package-lock.json') }}
          restore-keys: v1-node-dependencies-
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test

  snyk-security-scan:
    needs: [run-npm-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

# Run a docker build -> push-> scan -> login-> push
  docker-scan-build-push:
    needs: [ run-npm-tests, snyk-security-scan ]
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
    # first export 
      - name: Build and push
        uses: docker/build-push-action@v2
        with: 
          push: true
          tags: chowjl94/cicd-workflow-d3:latest

      #Run a security check against the docker image
      - name: Run Snyk to check Docker images for vulnerabilities
        id: snyk-scan
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: chowjl94/cicd-workflow-d3:latest
          args: --severity-threshold=high

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # push after export
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with: 
          push: true
          tags: chowjl94/cicd-workflow-d3:latest



  heroku-deploy:
    runs-on: ubuntu-latest
    needs: ['docker-scan-build-push']
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "cicd-workflow-d3" #Must be unique in Heroku
        heroku_email: "chowjl94@gmail.com"
        usedocker: true
